export const EXECUTION_PROFILE_SCHEMA_VERSION = "0.1.0";
export const EXECUTION_PROFILE_LOCK_SCHEMA_VERSION = "0.1.0";
export const EXECUTION_PROFILE_DIFF_SCHEMA_VERSION = "0.1.0";
export const OUTCOME_RECEIPT_SCHEMA_VERSION = "0.1.0";
